name: Makefile CI

on:
  # Run using manual triggers from GitHub UI:
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch: {}
  # Run on every push:
  push: {}
  # Run on pull request activity:
  pull_request: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install elan
      run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.0.0/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

    - name: Setup CaDiCaL
      run: |
          set -o pipefail
          git clone https://github.com/arminbiere/cadical.git $HOME/cadical
          cd $HOME/cadical; ./configure && make
          echo "$HOME/cadical/build" >> $GITHUB_PATH

    - uses: actions/checkout@v3

    - name: Build LNSym
      run: make all
